### ISSUE TITLE
tilde

### ISSUE THREAD

**Issue by nadezdaalexandrovna** [Alex-bzh/vikey#1]
Salut Alex, 
Encore une fois un grand merci pour ce clavier ! Le petit bug avec le tilde vient de l'erreur d'incrémentation de posCursor : au lieu de rajouter 1, il faut rajouter this.value.lenth.
// Now, we attach listeners to all the new kbd elements
                $(".vk-key").click(function() {
                    // Which symbol?
                    var char = this.innerHTML;
                    // Where to?
                    $("#"+Event.target.id).val(function() {
                        var string = this.value.substr(0, posCursor) + char + this.value.substr(posCursor, this.value.length);
                        **//posCursor += 1; **
                        **posCursor+=this.value.length;**
                        return string;
                    });
                });

**Comment by nadezdaalexandrovna** [comment]
Nouvelle version : posCursor += char.length;  :)

**Comment by Alex-bzh** [comment]
Salut Nadia !
Encore une fois merci pour la résolution de ce bug. Je viens seulement de publier un fix.
À très bientôt !
